### ISSUE TITLE
Убрать в панели администраторов Groups и русифицировать.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#121]
**Why?**
Groups на не нужны. И перевести на русский тоже логично.

**How To Do?**
Переопределяем админку.
![Снимок экрана от 2023-07-27 22-23-28](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/69113745/6df91a13-2511-4bbb-839a-60d0d58a3f70)

**Where?**
src/

**Comment by Fr0stFree** [comment]
Очень странно, но при запуске через асинхронный шлюз, в моей админке не подхватывается статика и отдается сырой html без css и js. Это не у меня одного такое?)

**Comment by KonstantinRaikhert** [comment]
@Fr0stFree Хм.. Тут у меня тоже путаница. Давай уточним, как ты отрабатываешь команду collectstatic?
