### ISSUE TITLE
Реализовать получение регионов с БД

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#127]
**Why?**
Сейчас у нас хардкод. Регионы берутся с констант. Нужно забирать с БД. Таска будет состоять из 2х частей.

**How To Do?**
1. Сначала необходимо поправить генерацию в фабриках регионов. Экземпляр региона сейчас содержит region_name и region_key. Но фабрика генерует название региона существующее, а ключ - нет. Предлагаю добавить постгенерацию ключа в фабрике с методом транслитерации и snake_case. 
2. Заполняя БД командой filldb, получаем регионы с "правильными" ключами. И в хендлере receive_assistance реализовываем получение регионов с БД.

**Where?**
spread_wings_bot/src/core/factories.py
spread_wings_bot/src/bot/handlers/assistance.py

![Снимок экрана от 2023-08-02 20-04-25](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/69113745/d1df5abb-4fde-48ec-b6d0-3d3e503132fd)

**Comment by KonstantinRaikhert** [comment]
@Fr0stFree Возьмёшь?)

**Comment by Fr0stFree** [comment]
Забираю)
