### ISSUE TITLE
Поменять для Question в админке django поля.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#130]
**Why?**
Кажется необходимо упорядочить формы полей по смыслу

**How To Do?**
1. Вопрос, Короткое описание, Тип вопроса, Ответ, Регионы
2. В ответе и регионах поменять виджеты. Для Ответа виджет широкий для текста. Для регионов виджет с двумя колонками (не помню как называется).

**Where?**
spread_wings_bot/src/bot/admin.py

![Снимок экрана от 2023-08-02 20-42-47](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/69113745/cbebd2d6-19f5-4ded-a61f-29b973a25e63)

**Comment by Zh-Andrew** [comment]
Я возможно что-то упустил, когда объяснялись поля в этой модели, но что-то не могу сообразить, что именно указывается в поле "Короткое описание"? Короткое описание чего именно?)

**Comment by KonstantinRaikhert** [comment]
Короткое описание - тот текст который будет на кнопке в боте)
