### ISSUE TITLE
Тестирование бота при помощи pytest. Разобраться и написать несколько первых тестов.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#155]
**Why?**
Необходимо начать тестировать наше приложение. Использовать предлагаю pytest с надстройкой asyncio

**How To Do?**
Проверить в зависимостях, возможно есть лишние пакеты для тестирования и упразднить их.
Начать нужно с юнит тестирования и протестировать хендлеры:
* start
* help_command
* receive_assistance
* select_type_of_help
* select_assistance

Некоторые материалы:
https://habr.com/ru/companies/beeline_cloud/articles/734164/ 
https://www.youtube.com/watch?v=w0l4S838Idc
https://github.com/python-telegram-bot/python-telegram-bot/tree/master/tests

**Where?**
 /spread_wings_bot/tests

**Comment by KonstantinRaikhert** [comment]
@MikeWazowskyi Привет! Есть какие нибудь успехи?

**Comment by MikeWazowskyi** [comment]
Да, есть. Не заметил сообщения. Залил PR.
