### ISSUE TITLE
Реализовать отображение программы в сообщении при её выборе.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#173]
**Why?**
Сейчас у нас нет этого функционала. Нужно, чтобы в сообщении отображались поля названия программы и ее основного текста.

**How To Do?**
Реализуется новый хендлер. Так же нужно добавить на это сообщение кнопку назад и задать вопрос, при этом убрать кнопку задать вопрос со списка программ. Понадобится введение дополнительного типа сообщения для отправки вопроса (в теме письма)

![Снимок экрана от 2023-08-18 15-23-09](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/69113745/419f93d7-2d91-44de-af38-d0355aa891ab)

**Where?**
/src/bot

**Comment by MikeWazowskyi** [comment]
Возьму
