### ISSUE TITLE
Ошибка (500 Internal Server Error) при создании координатора с дублирующимися данными (телефон/телеграм) в админке. 

### ISSUE THREAD

**Issue by Zh-Andrew** [Studio-Yandex-Practicum/spread_wings_bot#185]
**Why?**
На текущий момент при создании в админке координатора с дублирующимися данными, а именно только в полях "Номер телефона" и "Telegram" выдается ошибка 500 Internal Server Error

![Ошибка в веб-интерфейсе](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/100352694/653d1193-6f3b-412a-a99f-2b5dbbcd454f)

![Ошибка в терминале](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/100352694/496b437f-be22-44d2-8034-c1d9af1c5471)

**How To Do?**
Думаю надо как-то обработать это исключение, либо как-то переписать код. Ошибка возникает из-за метода save в нашей модели координатора, эта ошибка и бдует возникать, об этом говорит [дока джанги.](https://docs.djangoproject.com/en/4.2/ref/models/fields/#unique)
UPD: Просто нужно убрать уникальность этих полей

**Where?**
spread_wings_bot/src/bot/models.py
Судя по всему смотреть надо на модель Coordinator, метод save.

**Comment by Fr0stFree** [comment]
Тут вопрос, скорее, к логике приложения. Мы хотим создавать координаторов с одинаковыми телефонами/телегами/мейлами для разных регионов или нет? Если нет, надо убирать уникальность у полей модели и мигрировать @KonstantinRaikhert ?

**Comment by Zh-Andrew** [comment]
Ну изначально я имел ввиду, что если пользователь, например, ошибся и ввел уже существующий номер, текст ошибки бы указывал на то в чем он ошибся, а не просто ошибку сервера)
Но в целом логика приложения в части связей координатор - регион в текущей реализации мне кажется некорректной. Например, если вдруг какой-то координатор решит, что ему надоело быть координатором и уйдет по-английски, надо будет его заменить другим сотрудником, а на период поиска другого сотрудника, можно было бы временно закрыть позицию ушедшего сотрудника сотрудником из соседнего региона. В нашей модели координатора у координатора может быть только один регион, и у региона может быть только один координатор.
Хотя, честно говоря, я не знаю как работает фонд, может у них такие ситуации исключены.

**Comment by KonstantinRaikhert** [comment]
На самом деле поступила обратная связь от заказчика, что возможно они захотят иметь одного координатора на несколько регионов. Думаю все же после первого релиза это сделать. В надежде что больше не будет изменений в структуре БД. Хотя сомневаюсь что они сразу начнуть заполнять, думаю будет у нас время)
