### ISSUE TITLE
Сделать рефакторинг состояний бота и названий функций

### ISSUE THREAD

**Issue by chem1sto** [Studio-Yandex-Practicum/spread_wings_bot#193]
**Why?**
Сейчас состояния бота и функции, вызываемые после "отлавливания" хэндлерами этих состояний, запутывают разработчика при работе с ними.

**How To Do?**
Необходимо подправить названия состояний и функций, чтобы они подходили по смыслу. Возможны конфликты из-за этого, но это надо решить....

**Where?**
bot/bot.py
bot/constants/states.py
bot/handlers/ask_question.py

![Image](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/110044359/6ec1ca3c-cdcb-4f96-ab16-ced7fc1e451c)

**Comment by KonstantinRaikhert** [comment]
@elenashovtyuk Возьмёшь?)

**Comment by elenashovtyuk** [comment]
@KonstantinRaikhert, возьмуу)
