### ISSUE TITLE
Исправить bug, связанный с заполнением БД фикстурами из factory boy

### ISSUE THREAD

**Issue by chem1sto** [Studio-Yandex-Practicum/spread_wings_bot#200]
**Why?**
В процессе запуска бота при вводе достаточно большого количества разных вопросов, программ и маленького количества регионов (скриншоты ниже) можно получить ошибку `django.db.utils.IntegrityError: duplicate key value violates unique constraint "bot_fundprogram_title_key"`. 

![Image](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/110044359/004dbbe9-e4f4-4135-be04-2798bf8db093)

![Image](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/110044359/9cbaffa9-f2c2-4fc2-91c6-d2eab8c4b509)

Было бы очень круто, если бы бота можно было бы запускать с произвольным количеством и того, и того. Нужно, чтобы не перезапускать его по несколько раз в надежде на удачный рандом.

**How To Do?**
Скорее всего есть какие-то настройки для этого в библиотеке Factory boy. Или надо что-то сделать с моделями Django. Лично я за первый вариант :-)

**Where?**
bot/factories.py
bot/models.py

**Comment by MikeWazowskyi** [comment]
Возьму
