### ISSUE TITLE
Реализовать функционал главного координатора.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#204]
**Why?**
ФИДБЭК от заказчика.
Во первых нужен главный координатор исключительно для того, чтобы в контактах указывался главный, а потом региональный (может флаг?). Далее нужно предусмотреть возможность вести одному координатору несколько регионов, но не наоборот.

**How To Do?**
Нужно подумать как лучше и менее болезненно реализовать. Модели менять можно, но желательно по минимуму.
Так же обязательно продумать момент, что если координаторы совпадают, то в сообщении контактов выводить только одного человека)

**Where?**
src/bot

**Comment by Zh-Andrew** [comment]
Возникло много вопросов)
А функционал такого координатора будет чем-то отличаться, типа добавлять, менять, удалять в админке (_is_staff_, с выданными правами)? 
Или это будет обычный координатор, но только с какой-то пометкой, типа _is_chief_, которая по факту ничего не дает в нашем приложении, но нужна для какого-то собственного учета фонда?)
А админкой вообще кто рулить будет, известно?)

**Comment by Zh-Andrew** [comment]
Мне нравятся задачки с ролями я бы взял)

**Comment by KonstantinRaikhert** [comment]
Вот поэтому она пока в бэклоге) Не совсем понятно, как заказчик это видит и нужна с ними встреча. Но если что бери, как будет ясность)

**Comment by KonstantinRaikhert** [comment]
@Zh-Andrew В общем, надо подумать!) Жду твоих предложений. Может конечно ролями выполнить, я просто флаг предложил. Момент только в том, что главным может быть только один)

**Comment by Zh-Andrew** [comment]
Я подумаю, завтра дам предложения)

**Comment by Zh-Andrew** [comment]
В общем нам менять функционал координатора, делая его главным, пока не надо, поэтому и ролей прописывать не надо)
Задача (как я понял) в следующем:
1. Надо какого-то координатора отметить как главного, например, сделать какую-нить колонку "is_chief" с чекбоксом в админке. Только тут не совсем понял эту часть задачи: "_Во первых нужен главный координатор исключительно для того, **чтобы в контактах указывался главный, а потом региональный** (может флаг?)_." У нас в контактах за регионом может быть закреплен только один координатор (то есть порядок определения того кто первый будет отображаться в данном случае не актуален), или ты тут имеешь ввиду отображение в админке - сначала главный потом региональные?
2. Прописать Foreign Key в модели Region на модель Coordinator, чтоб у координатора было несколько регионов.

**Comment by KonstantinRaikhert** [comment]
i. Ну наверно не колонку, а флаг. То есть bool значение. В админке наверно маловажно как будет отображаться. Точнее не так. А мы можем сделать колонку с радиокнопками для главного координатора?))


![Image](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/69113745/d9c0d3db-c136-4c48-9e3b-a26f56b7f59b)
Ну а в коде, вытаскиваем по флагу координатора, а потом уже по региону

ii. Тут надо как то придумать, чтобы не было двух координаторов на один регион. Как то реализовать проверку. И если она не проходит. Выдавать предупреждение, почему нельзя. Задача нетревиальная конечно) Чуть надо покопаться в кишках админки) Но там можно это сделать. Например через сообщения предупреждения над полем заполняемым

**Comment by KonstantinRaikhert** [comment]
Вот только определиться с этим поскорее надо бы. Релизить нужно..
Тут можно поступить так: определить, какие необходимо сделать изменения в моделях (если вообще надо). И если надо, сделать эти изменения. А остальной функционал допиливать после релиза. Чтобы не было сильно больно готовые данные переносить с боевой БД

**Comment by Zh-Andrew** [comment]
Ок, понял)

**Comment by KonstantinRaikhert** [comment]
@Zh-Andrew Привет, есть новости?)

**Comment by Zh-Andrew** [comment]
По первому пункту реализовал чекбокс, радио кнопку пока не осилил, есть ощущение (после поисков в гугле), что тут надо через JS прописывать в template
По второму пункту очевидный вариант через ForeignKey в модели Region на модель Coordinator прописывать. А соответствующее поле (region) в модели Coordinator удалять. Но тут возникла ошибка цикличности импорта (в bot/models у нас импортируется core/models, и соответственно наоборот, так как мне надо импорт сделать в core/models библиотеки bot/models🥴). И соответственно возник вопрос, почему у нас модель Region затесалась в core/models, а все остальные модели для бота в bot/models. Может нам Region тоже перенести в bot/models?)
