### ISSUE TITLE
Подумать над тем, как реализовать более красиво отображение текстов в сообщениях. Жирный, курсив, ссылки.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#205]
**Why?**
Наши ответы на вопросы и программы имеют "сухой" однородный текст. Нужно привести его в более читаемый вид.

**How To Do?**
Для этих целей нужно подобрать во первых технологию: markdown или html. Далее подобрать для админки необходимый визавиг редактор (есть много реализаций). Ну и бот, чтобы распознавал тэги (html или markdown) ему нужно что то прописать. Можно найти в документации.

**Where?**
Реализация - обсуждение в пачке с необходимым тредом.

**Comment by chem1sto** [comment]
Я думаю могу взять таску, посмотрим что получится

**Comment by KonstantinRaikhert** [comment]
Бери. На самом деле мало сложного. Есть множество готовых решений для встраивания в джангу. Нужно просто подобрать оптимальное. Основываясь на том, что все равно API телеграма может обрабатывать теги жирно, курсива, подчеркнутого текста. Еще машинный шрифт. И эмодзи. Другие теги не нужны

**Comment by KonstantinRaikhert** [comment]
А, ну и ссылки

**Comment by chem1sto** [comment]
окей, я завтра создам тред в пачке со своими предложениями по технологиям
