### ISSUE TITLE
Исправить очередной bug, связанный с заполнением БД фикстурами из factory boy

### ISSUE THREAD

**Issue by chem1sto** [Studio-Yandex-Practicum/spread_wings_bot#231]
**Why?**
В процессе запуска бота при вводе разных вопросов, программ и регионов (скриншот ниже) можно получить ошибку `django.db.utils.DataError: value too long for type character varying(32)`.

![Image](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/110044359/afd41b41-5eb1-4235-b451-6de7a428afbb)

Для удобства стоит с этим разобраться., чтобы подобная ошибка не возникала.

**How To Do?**
Можно попробовать поэкспериментировать с моделями и с factory boy. Судя по всему factory boy генерирует слишком длинное значение для поля.

**Where?**
bot/factories.py
bot/models.py

**Comment by bobr2072** [comment]
Можно чуть побольше подробностей, это полный вывод ошибки ? И при какой именно команде она возникает ?

**Comment by chem1sto** [comment]
Да я как будто бы сам уже пофиксил уже это, по крайней мере эта ошибка в моём варианте больше не возникает... Немного переписал фабрику

**Comment by chem1sto** [comment]
Так что ишью можно закрывать 😆

**Comment by bobr2072** [comment]
Ахах, окей
