### ISSUE TITLE
Пофиксить staticfiles и ckeditor 

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#240]
**Why?**
Сейчас не работает на стейдже, а следовательно не будет на проде

**How To Do?**
Возможно проблема считывания директорий

**Where?**

**Comment by teryaev-anton** [comment]
Потестил у себя.

1. Перенес папку ckeditor_add-on в src.
2. Выполнил collectstatic.
3. Все заработало


![Image](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/110157871/da9667ec-4788-4f33-8b7f-7e48bce124b3)

**Comment by chem1sto** [comment]
тут скорее всего проблема с контейнером проекта и как следствие с путями для STATICFILES_DIRS, попробую сегодня локально потестить
