### ISSUE TITLE
Попрравить отображение в админке некоторых полей 

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#244]
**Why?**
Чтобы было понятнее

**How To Do?**
**в вопросах:** короткое описание на текст на кнопке
тип вопроса - для обьектов сделать отображение на русском языке (кстати как у нас появился общий вопрос, непонятно) Общий вопрос нужно удалить.
**в программах** короткое описание на текст на кнопке

**Where?**

**Comment by KonstantinRaikhert** [comment]
К сожалению большой баг, вернул таску...

**Comment by KonstantinRaikhert** [comment]
@alekseikoznov Если ты готов, возьми таску пожалуйста! Ольга недоступна до воскресенья, а исправить надо)
Только общий вопрос нужно удалить ИЛИ скрыть так, чтобы бот продолжал работать)) В предыдущей реализации упали стейты

**Comment by alekseikoznov** [comment]
Да, хорошо!
