### ISSUE TITLE
Написать для заказчика инструкции для получения telegram токена и пароля почты

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#253]
**Why?**
Так как наш заказчик не понимает, как это сделать, необходимо оформить либо видеоинструкцию либо pdf файл со скриншотами

**How To Do?**
1. Для получения токена телеграм.
2. Пароль для приложений в яндекс почте. В настройках есть специальная вкладка для выпуска пароля для сторонних сервисов

**Where?**

**Comment by bobr2072** [comment]
Костя, лови видосики !
