### ISSUE TITLE
Добавить восклицательный знак в шаблоны писем.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#254]
**Why?**
Фонду этот нюанс важен. Необходимо добавить

**How To Do?**

![2023-08-31_21-32](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/69113745/c8af6706-bfd2-424a-bb70-c880cffcb6b0)

**Where?**

**Comment by MikeWazowskyi** [comment]
Возьму, поправлю.

**Comment by KonstantinRaikhert** [comment]
Проверь еще пожалуйста, на всех ли моментах правильно отображается шаблон и данные
