### ISSUE TITLE
Еще раз схлопнуть миграции

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#255]
**Why?**
Перед релизом необходимо

**How To Do?**
Схлопываем миграции, но не забываем про настройки бота в миграциях

**Where?**

**Comment by teryaev-anton** [comment]
@KonstantinRaikhert 
Давай себе заберу.

Уже делал это, так что много времени не займет, и вероятность "испортить" низкая.
