### ISSUE TITLE
Срочный фикс! Нужно, чтобы все настройки в админке меняли поведение бота

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#268]
**Why?**
Сейчас проблема, что оказывается не все настройки привязаны к боту, непонятно как так произошло, но нужно пофиксить.

**How To Do?**
Просто по аналогии с другими настройками добавить через django ORM асинхронные запросы.
Что не так на скрине.

![2023-09-03_20-55](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/69113745/9b19a81d-7ad2-4287-be9c-d95f374213d3)
![2023-09-03_20-57](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/69113745/45e71a44-307f-4141-bc8d-f85f949d2191)

**Where?**
Где делаем реализацию задачи, какие сервисы задействованы, ссылка на требования, сcылка на API, скриншоты.

**Comment by KonstantinRaikhert** [comment]
@chem1sto Если сможешь за сегодня завтра, будет круто! Если нет, передадим)

**Comment by chem1sto** [comment]
я попробую завтра сделать, сегодня никак =(

**Comment by KonstantinRaikhert** [comment]
Хорошо!
