### ISSUE TITLE
Срочный фикс! Нужно, чтобы данные попадали в шаблон письма в форме задать вопрос

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#286]
**Why?**
Как то получилось так, что сломалось...

**How To Do?**
![2023-09-05_23-30](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/69113745/9f33c8db-8f28-4b84-b441-c1b185ea80f0)

**Where?**

**Comment by KonstantinRaikhert** [comment]
@teryaev-anton Получится поправить?

**Comment by teryaev-anton** [comment]
@KonstantinRaikhert 

Сегодня есть несколько свободных часов. Попробую разобраться.
