### ISSUE TITLE
Вынести DONATION_URL в settings

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#61]
**Why?**
Нужно заложить изменение данного урла через .env

**How To Do?**
Добавляем поле в settings

**Where?**
`src/bot/constants/urls.py`

**Comment by andreibo87** [comment]
settings pydantic - речь идет о class Settings в конфиге бота?

**Comment by KonstantinRaikhert** [comment]
Да

**Comment by Fr0stFree** [comment]
Закрывается вместе с #95
