### ISSUE TITLE
Упростить задание команд бота в кнопке меню

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#62]
**Why?**
Сейчас у нас есть лишняя команда /upmenu. Необходимо от неё избавиться.

**How To Do?**
Думаю стоит вообще убрать хендлер update_menu и сделать просто в starthandler проверку условия. Если нет у бота команд то добавим команды в кнопку меню
`await context.bot.get_my_commands()`

**Where?**
`src/bot/handlers/service_handlers.py`

**Comment by KonstantinRaikhert** [comment]
@distemper17 Привет! Есть сложности с таской? Дедлайн уже прошел))

**Comment by distemper17** [comment]
@KonstantinRaikhert привет. Проблем с самой таской нет, больше проблемы с отладкой, бьюсь над тем как понять как правильно настроить бота для отладки...

**Comment by KonstantinRaikhert** [comment]
@distemper17 опиши проблему подробнее) Чем раньше разберешься, тем лучше. Попробуем помочь!

**Comment by distemper17** [comment]
Конечно. Извиняюсь, что общо получилось.

В общем я настроил все необходимое в проекте, включая pre-commit, создал файл .env, в который привязал токен от старого бота, указал почту, подключил IMAP и т.д. Запускаю проект через uvicorn иии.. Не совсем понимаю, что дальше. В админку он не пускает (видимо потому что нет базы данных). Отображения обычных страниц нет (ясен пень, т.к. это бот), сам бот, которого я привязал тоже не работает. 
Я малость поплыл и несколько дней ковыряюсь в уроках ЯП, но не  могу найти ответа. Если есть рекомендации по поводу того, как в нашем случае тестировать изменения в коде - буду признателен
