### ISSUE TITLE
Обработка любого сообщения пользователя

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#68]
**Why?**
Необходимо обработать любое сообщение пользователя, которое может быть направлено боту (текст, аудио, видео, картинка и т.д.)

**How To Do?**
Доработать существующую функцию, сделать так, чтобы бот удалял любое сообщение пользователя, при этом, бот должен направлять всплывающее уведомление с текстом что-то типа “Извините мой функционал ограничен”, либо бот должен изменять предыдущее свое сообщение, добавлять в него ту же строку (”Извините мой функционал ограничен”), аналогично тому, как он это делает при нажатии кнопок сейчас.

UPD: если не получается решать таску по описание, предложить реализацию.

**Where?**
`src/bot/handlers`

**Comment by KonstantinRaikhert** [comment]
@UlyaPP Привет! Есть сложности с таской?

**Comment by UlyaPP** [comment]
@KonstantinRaikhert Привет! По дедлайну не укладываюсь. И да, есть проблема. Долго былась, что не отрабатываеют методы, в итоге оказалось, что проект не пересобирается. Делала docker-compose -f docker-compose.stage.yaml build и up

**Comment by KonstantinRaikhert** [comment]
@UlyaPP а зачем тебе в локальной разработке docker-compose.stage ?
Локально проект запускается с помощью uvicorn. Посмотри пожалуйста ReadMe. Это как раз нововведение после добавления Джанги) Stage нам необходим для деплоя на сервер. Его скоро починим)

Сможешь примерно определить, сколько понадобиться на таску?😅

**Comment by distemper17** [comment]
@KonstantinRaikhert Костя, привет! Насколько понимаю, ты переключил эту задачу на меня. Если не сложно, можешь плз подкорректировать дедлайн (текущий по задаче уже просрочился). Спасибо.

**Comment by KonstantinRaikhert** [comment]
@distemper17 Привет! Готово, заложил 3 дня)

**Comment by distemper17** [comment]
@KonstantinRaikhert привет! Можешь, пожалуйста, подсказать, каким образом функционал должен отличаться от того состояния, что есть сейчас?
В текущем состоянии бот уже удаляет сообщения и медиа, отправленные ему и выводит отбивку. Возможно, эта задача была отработана в комплексе с другой..

**Comment by distemper17** [comment]
@KonstantinRaikhert единственное, мне кажется, что реализация может быть улучшена. Сообщения удаляются и ошибки всплывают, но при совершении пользователем корректного действия, они остаются там же где и были. Визуально и логически это не выглядит аккуратно. Плюс, я не совсем понимаю, почему сейчас у нас установлена валидация на минимум 30 символов, когда задаешь вопрос? Многовато, имхо, вопрос может быть достаточно коротким. Либо, как вариант возвращать на прошлый шаг (задать вопрос), а не футболить на начало..

**Comment by KonstantinRaikhert** [comment]
@distemper17 А ты не путаешь задачу? По поводу формы это все же для другой таски. Здесь же просто хотелось получить такой функционал:
Пользователь отправляет какое то сообщение (не в форме), бот его удаляет и редактирует свое предыдущее сообщение надписью - "Извините, функционал бота ограничен. Пожалуйста выберите действие"

Если не совсем понятно, можно созвониться и обсудить.

**Comment by distemper17** [comment]
@KonstantinRaikhert да, очень буду признателен, если будет возможность завтра уделить 10 минут, чтобы обсудить более конкретно. Ибо в контексте моего понимания задачи - бот уже умеет так, как мы хотим :)
во сколько будет удобно?

**Comment by KonstantinRaikhert** [comment]
@distemper17 Давай я еще кого нибудь подключу к этой задаче?

**Comment by distemper17** [comment]
@KonstantinRaikhert Привет! Давай подключим, оч надо.
