### ISSUE TITLE
В форме задать вопрос добавить кнопки возврата к исходному состоянию и предыдущему шагу

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#69]
**Why?**
Необходимо добавить inline кнопки на каждом шаге формы. “Назад” и “В начало”

**How To Do?**
![Снимок экрана от 2023-06-12 21-46-00](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/69113745/06b0186c-6390-4300-b0d3-1707908f48b1)
Сейчас нет возможности отменить форму задать вопрос или вернуться к предыдушему шагу (если допустил ошибку и нужно исправить). Т.е. реализуем вместе с кнопками стейты возврата к необходимым состояниям.

**Where?**
`/src`

**Comment by KonstantinRaikhert** [comment]
@samebr0dy Как прогресс?)

**Comment by samebr0dy** [comment]
Застрял из-за ошибок, что когда я возвращаюсь назад по форме, вылазит ошибка:

```
  File "F:\Dev\spread_wings_bot\src\bot\handlers\back_handler.py", line 17, in back_button
    await ASK_FUNCTIONS.get(command)(update, context)
  File "F:\Dev\spread_wings_bot\src\bot\handlers\ask_question.py", line 30, in get_question
    question = update.message.text
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by KonstantinRaikhert** [comment]
Значит тут нужно менять логику и возможно заходить со стороны callback

**Comment by KonstantinRaikhert** [comment]
Если сильно застрял, заводи пост в пачке со своей проблемой. Иначе не сдвинемся..)

**Comment by KonstantinRaikhert** [comment]
@samebr0dy С тебя снимаю таску, т.к. уже необходима реализация..

**Comment by KonstantinRaikhert** [comment]
@chem1sto Если не совсем понятно, что необходимо, стучись в пачку!)
