### ISSUE TITLE
Django структура проекта

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#77]
**Why?**
Волевым решением было принято организовать доставку данных к нашему боту через **django**

**How To Do?**
Сейчас необходимо ввести фрейворк в проект. Для этого добавляем в poetry и разворачиваем.
Создаём 2 приложения:
- users (здесь будем работать с нашими админами)
- api-bot ( здесь необходимые данные) 

**Where?**
по структуре проекта можно взглянуть на [этот](https://github.com/ohld/django-telegram-bot/#how-to-run) репозиторий. Но может есть идеи получше.

**Comment by KonstantinRaikhert** [comment]
@Fr0stFree Думаю ты с этим быстро справишься)) Остальные таски будем вводить по джанге сейчас

**Comment by Fr0stFree** [comment]
В перспективе ты хочешь переселить бота внутрь приложения джанги или они будут жить раздельно по контейнерам?

**Comment by KonstantinRaikhert** [comment]
Я думаю раздельно по контейнерам. Думаю не надо сейчас усложнять😅
