### ISSUE TITLE
Утилизация mySQL в коде

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#87]
**Why?**
Переходим на postgres и django, сам драйвер, алхимию и все методы связанные с mysql утилизируем

**How To Do?**
Необходимо пробежаться по зависимостям в poetry и так же по коду, найти артефакты и убрать

**Where?**
В основном все лежит в dot/db

**Comment by Fr0stFree** [comment]
фикстуры для заполнения БД надо переписать с новым драйвером?

**Comment by KonstantinRaikhert** [comment]
Нужно удалить все, кроме самих фабрик. Пусть останутся для того, кто будет снова фабрики писать по моделям джанги. 
То есть сессию бд, всякие парсеры можно удалять

**Comment by KonstantinRaikhert** [comment]
Точнее так, как только появятся модели, можно будет переделывать фабрики, создавать через менеджер команд джанги нашу команду по заполнению БД тестовыми данными.
