### ISSUE TITLE
Починить и обновить deploy бота на stage

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#88]
**Why?**
После изменения структуры проекта и изменения запуска бота нужно внести правки github actions

**How To Do?**
Нужно поправить:
- Dockerfile для сборки образа бота
- проверить, все ли в порядке docker-compose.stage.yaml
- Внести необходимые правки в github actions (build and deploy)

**Where?**
./github
./Dockerfile

**Comment by Fr0stFree** [comment]
Не забыть про 
```python
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]
``` 
и
```python
DEBUG = literal_eval(os.environ.get("DEBUG", "True"))
```
в `settings.py`. Для stage такие настройки должны отличаться

**Comment by Fr0stFree** [comment]
Костя, а для восстановления воркфлоу надо добавить новые секреты в проект. У нас к ним вроде доступа нет

**Comment by KonstantinRaikhert** [comment]
Да, точно. Напиши мне пожалуйста в пачке, какие нужно добавить
