### ISSUE TITLE
Создать приложение bot_settings (или core) и реализовать там модель settings.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#95]
**Why?**
Появилась идея не хранить в коде все основные сообщения бота и, например, ссылку на страницу с пожертвованиями, а модерировать в админке джанго. 

**How To Do?**
Для этого необходимо создать приложение джанго, в нем модель Settings. Необходимые примерные поля:
- title
- choicefield (url или text)
- url
- text
- settings_key (для испольвания в коде)

Сделать заготовку для миграций, при помощи которй будем загонять данные в БД с настройками бота.

**Where?**
src

**Comment by Fr0stFree** [comment]
Можешь, пожалуйста, привести пример экземпляров такой модели?

**Comment by KonstantinRaikhert** [comment]
Например:
title="Ссылка на страницу пожертвований"
choice_field="URL"
text=None
url="https://example.com"
settings_key="donation_url"

Зашивать потом это через миграции.
Обращаться в коде будем по settings_key.
Ну а в админке запретим менять settings_key и удалять в принципе эти экземпляры
