### ISSUE TITLE
Выяснить как при помощи Python Telegram Bot вести с пользователем диалог в одном сообщении.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/spread_wings_bot#97]
**Why?**
Бывают такие реализации, попадались на просторах телеграма. Вроде повышается юзабилити :)

**How To Do?**
В основном все это касается Inline режимов. Но возможно есть какие то нюансы. Необходимо подготовить какой то паттерн, чтобы его использовать во всех CallbackQueryHandlers.

**Where?**
Можно дополнить в ReadMe

**Comment by KonstantinRaikhert** [comment]
@Fr0stFree Будет тебе интересно покопаться на просторах?) Вообще неплохо бы такое реализовать.

**Comment by Fr0stFree** [comment]
Я вот [этого](https://t.me/Smsbyliknot_bot) бота писал. В нем есть что-то такое, что ты подразумеваешь?

**Comment by KonstantinRaikhert** [comment]
Да, сообщения он меняет. Как понимаю для это есть условие - всегда inline кнопки?
Имеется ввиду, чтобы история переписок не засорялась другими сообщениями, а было одно сообщение для взаимодействия от бота. 
Различные команды, ненужные сообщения пользователя можно удалять. Тут кстати не удаляются вроде как:
![image](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/69113745/363ec947-b864-4778-baea-d8546d63e970)

**Comment by Fr0stFree** [comment]
Да, суть в том, что взаимодействие с пользователем мы ограничили до инлайновых кнопок. Этого более чем достаточно. Внутрь каждой такой кнопки помещалась callback_data, распарсив которую можно определить местонахождение пользователя, запрос, язык и тд. В диалоге всё время присутствовало только одно сообщение, которое при каждом обновлении просто редактировалось

В те редкие моменты, когда нужен пользовательский ввод (например, авторизация), ставился  стейт, ожидающий данные. Затем они валидировались и отправлялись обратно. Тут уж никак не уйти от новых сообщений в диалоге, если только вручную не удалять.

Если выбор опций уж слишком большой и кнопок не хватает, то можно воспользоваться инлайновым модом (сейчас приложу видео)

**Comment by Fr0stFree** [comment]
https://github.com/Studio-Yandex-Practicum/spread_wings_bot/assets/67839759/fb6c8225-314b-4b75-876d-c23aaac99f99
